-- DBMS Lab Assignment - II

USE Raja_173;

-- 1(a) Create CUSTOMERS table

CREATE TABLE CUSTOMERS (CUST_ID VARCHAR(20) PRIMARY KEY, NAME VARCHAR(50), AGE INT, ADDRESS VARCHAR(50), SALARY DECIMAL(10,2));

-- 1(b) Create SHIPMENT table

CREATE TABLE SHIPMENT (SHIPMENT_NO VARCHAR(20) PRIMARY KEY, CUST_ID VARCHAR(20), WEIGHT INT);

-- 1(c) Add Foreign Key

ALTER TABLE SHIPMENT ADD FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID);

-- Declare NOT NULL: name 

ALTER TABLE CUSTOMERS MODIFY NAME VARCHAR(50) NOT NULL;

-- 1(d) Add START_CITY column

ALTER TABLE SHIPMENT ADD START_CITY VARCHAR(30);

-- 2(a) Insert data into CUSTOMERS

INSERT INTO CUSTOMERS VALUES
('C001', 'Ramesh', 32, 'Ahmedabad', 12000.00),
('C002', 'Khilan', 25, 'Delhi', 14500.00),
('C003', 'Kaushik', 23, 'Kota', 18000.00),
('C004', 'Muffy', 25, 'Mumbai', 15000.00);

-- 2(b) Insert data into SHIPMENT

INSERT INTO SHIPMENT VALUES
('S201', 'C001', 120, 'Indore'),
('S202', 'C002', 210, 'Kolkata'),
('S203', 'C003', 320, 'Mumbai');

-- 3(A) Describe CUSTOMER and SHIPMENT tables

DESC CUSTOMERS;
DESC SHIPMENT;

-- 3(B) Display tables

SELECT * FROM CUSTOMERS;
SELECT * FROM SHIPMENT;

-- 3(C) Find out START_CITY of SHIPMENT

SELECT START_CITY FROM SHIPMENT;

-- 3(D) Change age of Kaushik to 35

UPDATE CUSTOMERS SET AGE = 35 WHERE NAME = 'Kaushik';

-- 3(E) Change salary of Ramesh to 15500.00

UPDATE CUSTOMERS SET SALARY = 15500.00 WHERE NAME = 'Ramesh';


-- 3(F) Delete S202 from SHIPMENT

DELETE FROM SHIPMENT WHERE SHIPMENT_NO = 'S202';